In [1]:
a = [1,2,3,4]

In [2]:
b = [10,11,12,13]

In [3]:
a + b

[1, 2, 3, 4, 10, 11, 12, 13]

In [4]:
output = []

In [5]:
for item1, item2 in zip(a,b):
    output.append(item1+item2)

In [6]:
output

[11, 13, 15, 17]

In [8]:
g = list(range(1000000))

In [10]:
%timeit sum(g)

11 ms ± 436 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
import numpy as np

In [12]:
g_array = np.array(g)

In [13]:
%timeit np.sum(g_array)

676 µs ± 20.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
momo = np.array([1,2,3,4])

In [15]:
roro = np.array([10,11,12,13])

In [20]:
momo +roro

array([11, 13, 15, 17])

In [17]:
momo/roro

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [19]:
momo.itemsize

8

In [21]:
roro.ndim

1

In [22]:
roro.nbytes

32

In [23]:
vovo = np.array([1],[2,3],[4,5,6])

ValueError: only 2 non-keyword arguments accepted

In [24]:
np.exp(roro)

array([ 22026.46579481,  59874.1417152 , 162754.791419  , 442413.39200892])

In [25]:
vovo = np.array([[1],[2,3],[4,5,6]])

In [26]:
vovo

array([list([1]), list([2, 3]), list([4, 5, 6])], dtype=object)

In [27]:
vovo.ndim

1

In [32]:
vovo = np.array([[1,1],[2,3],[4,5]])

In [29]:
vovo.ndim

2

In [40]:
pae = np.array([[[1,1],[2,3],[4,5]],[[1,1],[2,3],[4,5]],[[1,1],[2,3],[4,5]]])

In [41]:
pae.ndim

3

In [42]:
pae

array([[[1, 1],
        [2, 3],
        [4, 5]],

       [[1, 1],
        [2, 3],
        [4, 5]],

       [[1, 1],
        [2, 3],
        [4, 5]]])

In [43]:
pae.shape

(3, 3, 2)

In [44]:
pae.T

array([[[1, 1, 1],
        [2, 2, 2],
        [4, 4, 4]],

       [[1, 1, 1],
        [3, 3, 3],
        [5, 5, 5]]])

In [45]:
pae.size

18

In [46]:
pae[1,2,1]

5

In [47]:
pae[:3]

array([[[1, 1],
        [2, 3],
        [4, 5]],

       [[1, 1],
        [2, 3],
        [4, 5]],

       [[1, 1],
        [2, 3],
        [4, 5]]])

In [48]:
pae[:1]

array([[[1, 1],
        [2, 3],
        [4, 5]]])

In [49]:
pae[0:2]

array([[[1, 1],
        [2, 3],
        [4, 5]],

       [[1, 1],
        [2, 3],
        [4, 5]]])

In [52]:
sogo = np.array([1,1,1,1,1,1])

In [53]:
sogo

array([1, 1, 1, 1, 1, 1])

In [54]:
sogo+sogo

array([2, 2, 2, 2, 2, 2])

In [55]:
coco = np.array(sogo)

In [56]:
coco

array([1, 1, 1, 1, 1, 1])

In [60]:
coco = np.array(sogo)

TypeError: data type not understood

In [62]:
sobo = np.array(0,1,2,3,4,5)

ValueError: only 2 non-keyword arguments accepted

In [63]:
sobo = np.array([0,1,2,3,4,5])

In [64]:
sobo

array([0, 1, 2, 3, 4, 5])

In [66]:
clean = sobo + 5

In [ ]:
4:5,0:2

In [69]:
a = np.arange(25).reshape(5,5)

In [77]:
a[4]

array([20, 21, 22, 23, 24])

In [101]:
a[1::2,:-1:2]

array([[ 5,  7],
       [15, 17]])

In [100]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [102]:
a.data

In [103]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [ ]:
# binary operators and(&)  or(|) not(~)

In [105]:
b = np.array([1,2,3,4,5])

In [106]:
subset = b[[0,2]]

In [107]:
subset

array([1, 3])